# Site
repository: anyagalkina/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anna Galkina
title: Front-End Developer
phone: +7(962)911-46-95
email: anna.blackbird1@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: anyagalkina
linkedin_username: anna-galkina-28016088


# Additional icon links
additional_links:
  - title: telegram
    icon: fab fa-telegram
    url: https://t.me/anna_blackbird
  - title: portfolio
    icon: fa fa-user
    url: https://anyagalkina.github.io/portfolio
  - title: codewars
    icon: fa fa-code
    url: https://www.codewars.com/users/AnyaGalkina


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Summary
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  An experienced Front-End Developer (React/Redux stack) with a daily learning habit.
  
  Capable to write maintainable, scalable and readable code utilizing cutting-edge tools and frameworks, cover it with tests, and create multi-stage builds using Docker.
  Able to implement SPA with responsive design from concept through deployment as well as maintain, update, and improve existing company websites.
  I work effectively in a team being familiar with Git flow approaches, weekly sprints and in the same time completing tasks independently when needed.
  Usage of official documentation and google how to resolve an issue is not a problem for me.
  
  I look forward to sharpening my skills with my next team!


content:
  - title: Technical skills
    layout: text
    content: |
      **Programming Languages**: TypeScript, JavaScript (including modern approaches async/await, ES6)

      **SPA libraries and frameworks**: React, React Native, Next.js

      **Store management**: Redux, Redux Toolkit, React-Redux, Redux-Thunks, Redux-Saga

      **Client-Server communication**: REST API, Axios, React Query, WebSocket, Socket.IO, Swagger
      
      **Back-end basic**: Node.js  (REST API, middleware, input validation, nodemailer, sorting and pagination), MongoDB

      **Styles and Design**: CSS Preprocessors (SASS), CSS modules, Styled-components, Tailwindcss, Responsive web design, MUI, Ant Design, Figma

      **Routing**: React-Router-Dom v5 and v6

      **Additional libraries**: Formik, Yup, React Hook Form, Howler.js, React-chartjs-2

      **Tests**: Test Driven Development (TDD), Postman, Jest Unit Tests, Storybook, Cypress, Snapshot, ReduxDev Tools

      **Git**: GitLab, GitHub, GitHub Pages

      **Containers**: Docker, Docker Compose
      
      **Bundle builder**: Webpack 5 
      
      **Linters**: ESLint, Prettier

      **Atlassian stack**: Jira, Confluence

  - title: Commercial work (2022 - Present)
#    layout: text
#    content: |
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Full time job
        sub_title: It-Incubator
        link: https://it-incubator.io/

        #        caption: Jan 2023 - Present
        description: | # this will include new lines to allow paragraphs
          - Created reusable components with React such as modal window, textarea, avatar, etc.
          - Implemented https requests to the server
          - Built login, registration and password recovery features with JWT, validation and reCaptcha
          - Implemented saving and getting data using Local Storage and Indexed DB.
          - Developed filters and search logic, including server request optimization to get data
          - Developed payments implementation on web site
          - Implemented errors handling
          - Covered code with unit tests, Storybooks tests and E2E tests with Cypress
          - Bugfix, refactoring and optimization
          - Contributed to web layout and design based on Figma reference
          - Implemented mobile responsive layouts
          - Built and packed the app with Docker
          
          **Technical stack:** REST API, TS, React, Redux-Toolkit, React-redux, React-router-dom v6, Axios, Material UI, Formik, Next.js, React Query, Tailwindcss, SCSS, React-hook-forms, Yup, Cypress, Storybook, React-avatar-editor, Figma, Jira,  Jest
          

#    layout: list # Type of content section (list/text)
#    content:
      - layout: left
        title: Internship
        sub_title: It-Incubator
          #        caption: Oct 2022 - Dec 2022
        link: https://inctagram-vercel.vercel.app/
        link_text: Instagram clone Website
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://github.com/Armazok/Inctagram
        quote: >
#          Participated in open source educational teamwork project development. Worked on app with the ability to create packs with cards to learn in question/answer format and monitor your study progress

        description: | # this will include new lines to allow paragraphs
          - Built login and password recovery features with validation and captcha
          - Developed images upload feature including cropping and adding filters to image
          - Developed reusable components such as Modal, Textarea, Avatar
          - Covered code with tests: end-to-end tests with Cypress, Storybook tests
          - Contributed to web layout and design based on Figma reference
            
          **Technical stack**: REST API, TS, Next.js, React Query, Axios, Tailwindcss, React-hook-forms, Yup, Storybook, React-avatar-editor, Figma, Jira


      - layout: left
        title: Internship
        sub_title: It-Incubator
#        caption: Oct 2022 - Dec 2022
        link: https://anyagalkina.github.io/cards/
        link_text: Learning cards Website
        additional_links:
        - title: Github page for project
          icon: fab fa-github
          url: https://github.com/anyagalkina/cards
        quote: >
          Participated in open source educational teamwork project development. Worked on app with the ability to create packs with cards to learn in question/answer format and monitor your study progress

        description: | # this will include new lines to allow paragraphs
          - Built registration and password recovery features with validation
          - Developed filters and search logic, including server request optimization to get data (packs and cards) 
          - Wrote utils function for forms validation and server errors handling
          - Created header with app menu and Profile page with ability to change avatar image
          - Developed logic to show cards from pack in learning mode (smart random with non-recurring cards)
          - Contributed to web layout and design based on Figma reference
          
          **Technical stack**: REST API, TS, React, Redux Toolkit, React-redux, React-router-dom v6, Axios, MUI, Formik, Jest

  - title: Projects (2021 - 2022)

    layout: list # Type of content section (list/text)
    content:
#      - layout: left
#        title: Learning Cards
#        sub_title: Open source educational teamwork project
#        link: https://anyagalkina.github.io/cards/
#        link_text: Learning cards Website
#        additional_links:
#          - title: Github page for project
#            icon: fab fa-github
#            url: https://github.com/anyagalkina/cards
#        quote: >
#            App with the ability to create packs with cards to learn in question/answer format and monitor your study progress
#        description: | # this will include new lines to allow paragraphs
#          - Built registration and password recovery features with validation
#          - Developed filters and search logic, including server request optimization to get data (packs and cards)
#          - Wrote utils function for forms validation and server errors handling
#          - Created header with app menu and Profile page with ability to change avatar image
#          - Developed logic to show cards from pack in learning mode (smart random with non-recurring cards)
#          - Contributed to web layout and design based on Figma reference
#
#
#          **Technical stack**: REST API, TS, React, Redux Toolkit, React-redux, React-router-dom v6, Axios, MUI, Formik, Jest

      - layout: left
        title: To-Do List
        sub_title: Educational project
        link: https://AnyaGalkina.github.io/todolist-app
        link_text: To-Do List Website
        additional_links:
        - title: Github page for project
          icon: fab fa-github
          url: https://github.com/AnyaGalkina/todolist-app
        quote: >
          To-do list app with basic functionality
        description: |
          - Built a mobile responsive web app, implemented such features as create/edit/delete to-do lists, tasks and their descriptions, filter tasks by status
          - Developed Login Page with validation
          - Implemented update of all data on server through Axios requests, errors handling
          - Covered the code with unit tests for reducers and storybook tests
          - Added design with MUI theme config changes and components

          **Technical stack**: REST API, TS, React, Redux Toolkit, React-redux, React-router-dom v6, Axios, MUI, Formik, Jest

      - layout: left
        title: Finance Tracker
        sub_title: Pet project
        link: https://AnyaGalkina.github.io/finance_tracker
        link_text: Finance Tracker Website
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://github.com/anyagalkina/finance_tracker
        quote: >
         App lets you track your expenditures and incomes, set financial goals and gradually save money to achieve the targets
        description: | # this will include new lines to allow paragraphs          
          - Built the whole app from scratch, including state structure
          - Developed reusable components for Expenditures and Incomes Pages: input with icons' list with CRUD operations and charts
          - Optimized the rerender of components with help of useRef and useCallback hooks
          - Developed Savings Page with a modal window
          - Implemented saving data in Local Storage
          - Implemented mobile responsive layouts with css flex approach and designed app with MUI
          - Built and packed the app with Docker
          - Covered reducers with tests
          
          **Technical stack**: TS, React, Redux, React-redux, React-router-dom v6, Local Storage, React-Chartjs-2, MUI, React-Fontawesome, Jest, Uuid

      - layout: left
        title: Social Network
        sub_title: Self-educational project, spiced up with my own features
        link: https://anyagalkina.github.io/samurai-way
        link_text: Social Network Website Link
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://github.com/AnyaGalkina/samurai-way
        quote: >
          SPA for communication, following users, customizing profile
        description: | # this will include new lines to allow paragraphs
          - Developed such features as: 
          - Developed features with client-server communication: 
              - Login Page with validation 
              - Profile Page with ability to update data on the server
              - Chat service backed by WebSocket connections
              - User Page with ability to follow/unfollow users, search, pagination and filters, implemented client-server communication
              - Music library with Howler.js framework
              - News Page with pagination and share functionality  
          - Created mobile responsive layout and designed the app with Ant Design framework
         
          **Technical stack**: REST API, Axios, TS, React, Redux, React-redux, React-router-dom v5, WebSocket, Antd, Formik, Howler.js, Jest, Uuid

      - layout: left
        title: Online Shop
        sub_title: Self-educational project
        link: https://anyagalkina.github.io/shop
        link_text: Cakes and sweets shop Website
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://github.com/AnyaGalkina/shop
        quote: >
          Online shop with basic functionality
        description: | # this will include new lines to allow paragraphs
          - Developed front-end and back-end parts with REST API communication
          - Added MongoDB
          - Developed Cart Page with ability to edit products list and make order, send order to email.
          - Created Products Page with search bar and sorting by price
          - Implemented back-end errors handling
          - Packed the app with Docker using multi-stage build 
          - Designed an eye-catching and mobile responsive web app
          
          **Technical stack**: REST API, TS, React, Redux-toolkit, Node.js, MongoDB, nodemailer React-redux, React-router-dom v6, MUI, Formik, Yup, Express, Node.js, Jest Snapshot, Storybook, ESlint 

      - layout: left
        title: Star Wars
        sub_title: Self-educational project
        link:
        link_text: Cakes and sweets shop Website
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url:
        quote: >
          Mobile responsive App helps to find data about your favorite characters within the Star Wars universe
        description: | # this will include new lines to allow paragraphs
          - Developed Characters page with data from server
          - Added pagination and sorting by page
          - Created modal window with character details
          - Created Home Page and Header with routing
          - Implemented errors handling
          - Added Storybook tests and unit tests
          - Add end-to-end tests with Cypress
          - Implemented mobile responsive design according to Figma
          
          **Technical stack**: Technologies used: REST API, TS, React, Redux-toolkit, React-redux, React-router-dom v6, CSS, Jest, Storybook, Cypress

      - layout: left
        title: Drag & Drop Calculator
        sub_title:
        link: https://anyagalkina.github.io/calculator-constructor
        link_text: Calculator-constructor Website
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://anyagalkina.github.io/calculator-constructor
        quote: >
          SPA with constructor and runtime mode. In constructor mode you can drag & drop parts of calculator to canvas in any order. In runtime mode you can use classic calculator
        description: | # this will include new lines to allow paragraphs
          - Developed classic calculator functionality
          - Implemented drag and drop feature
          - Added styles according to the design from Figma
          
          **Technical stack**: TS, React, Redux-toolkit, React-redux, MUI, Jest, Figma, ESlint

      - layout: left
        title: Telegram Bot
        sub_title: Commercial project
        link: https://t.me/Pole_Training_Adviser_bot
        link_text: Telegram Bot Link
        additional_links:
          - title: Github page for project
            icon: fab fa-github
            url: https://github.com/AnyaGalkina/Pole-tg-bot
        quote: >
          Bot for pole sportsmen which helps them to choose different level exercises for training
        description: | # this will include new lines to allow paragraphs
          - Implemented handling of client messages
          - Developed logic how to range exercises by different levels providing their uniqueness during specific period 
          - Built and packed the app with Docker

          **Technical stack**: Javascript, Telegraf, Node-telegram-bot-api


  - title: Languages
    layout: text
    content: |
      **English**: Advanced
            
      **Russian**: Native


  - title: Education # Title for the section
    layout: list
    content:
      - layout: left
        sub_title: It-Incubator
        caption: 2021 - 2022
        description: |
          Front-End Developer with teamwork experience (React/Redux/TypeScript)
          
      - layout: left
        sub_title: The App Brewery
        caption: 2021
        description: |
          Web Development Course (HTML5, CSS3, JS, React, Rest API, Git)
      - layout: left
        sub_title: Moscow State Linguistic University
        caption: 2005 - 2011
        description: |
          Master of Science in Applied Economics
          
          Masters degree with honors

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs      
      Before entering into IT, I had an extensive working experience at worldwide known international companies such as Procter & Gamble and Avon.
      Grew from department assistant to brand manager, worked in marketing including day-to-day communication with external and internal business partners in English.
      I developed and implemented annual brand and pricing strategies identifying product gaps and incremental opportunities for growth.
      Led launch and leverage of new brands and products with 360 activation with digital and field support, based on consumer insights, needs, and marketing trends.

      Teamwork, thoughtful communication and responsibility are the primary pillars that I aim to bring to my new sphere.
      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
